### ISSUE TITLE
serverless variable substitution

### ISSUE THREAD

**Issue by dpmallinger** [mbudm/serverless-s3-local-sync#1]
Hello,

The code does not work when using variables in serverless.yml.  ex:
custom: ${file(serverless-${opt:stage, self:provider.stage}.yml):custom}

I read something about serverless calling all plugin constructors then doing variable processing.

I believe the code in the constructor:
this.s3Sync = this.serverless.service.custom.s3Sync;

should be moved into sync():
this.s3Sync = (this.serverless.service.custom && this.serverless.service.custom.s3Sync) || [];

**Comment by mbudm** [comment]
Ah ok that makes sense - do you want to do a PR?

**Comment by dpmallinger** [comment]
Hello,

I went through the steps to create a pull request and it appears that I need repo privs to push the fix branch.
remote: Permission to mbudm/serverless-s3-local-sync.git denied to dpmallinger.
fatal: unable to access 'https://github.com/mbudm/serverless-s3-local-sync.git/': The requested URL returned error: 403

note, the change got a tad bigger when I realized that the this.s3 code also needed to move.

**Comment by mbudm** [comment]
Ah I should add a readme about what I mean. Everyone has a different way of using github ;-)

The process I usually do is make a fork of the repo, push my changes to my own fork then do a PR from my fork into the original repo.

Like so: https://github.com/asmeurer/git-workflow

**Comment by dpmallinger** [comment]
pull request merged. the code has been fixed.
